tasks:
  image: iron/go:dev
  volumes:
    - $GOPATH:/go
  working_dir: /go/src/github.com/oppsio/tasks
  links:
    - redis
  command: /bin/sh -c "go build -o ./bin/tasks github.com/oppsio/tasks"
  environment:
    OPPSIO_ENV: development

redis:  
  image: sutoiku/redis
  user: stoic
  ports:
    - "6379:6379"
  volumes:
    - "redata:/data"
  command: redis-server

postgres:
  image: kiasaki/alpine-postgres
  ports:
    - "5432:5432"
  volumes:
    - "pgdata:/var/lib/postgresql/data"


# rabbitmq:
#   # build: ./dockers/rabbitmq
#   image: gonkulatorlabs/rabbitmq:latest
#   ports:
#     - "5672:5672"
#     - "15672:15672"
  # environment:

# kafka:
#   image: spotify/kafka
#   ports:
#     - "9092:9092"
#     - "2181:2181"
#   environment:
#     KAFKA_ADVERTISED_HOST: HOSTIP
#     KAFKA_ADVERTISED_PORT: 9092
#     KAFKA_CREATE_TOPICS: "test:1:1"

